// This function finds new PG and updates transient state, factoring in the previous dive's PG and the current surface interval.

export const SetPgAfterSi = (input, dives, currentDive, step, updateDive2, updateDive3) => {
    const inputData = { ...input }
    const dive = currentDive
    const findPg = () => {
        if (step === 1) return ''
        if (step === 2) return dives[0]?.pg
        if (step === 3) return dives[1]?.pg
    }
    let pg = findPg()
    const si = inputData.si
    dive.si = inputData.si

    if (step === 1) dive.pgAfterSi = 'none'
    else if (pg === 'A') {
        if (si >= 0) dive.pgAfterSi = 'A'
    } else if (pg === 'B') {
        if (si >= 48) dive.pgAfterSi = 'A'
        if (si <= 47 && si >= 0) dive.pgAfterSi = 'B'
    } else if (pg === 'C') {
        if (si >= 70) dive.pgAfterSi = 'A'
        if (si <= 69 && si >= 22) dive.pgAfterSi = 'B'
        if (si <= 21 && si >= 0) dive.pgAfterSi = 'C'
    } else if (pg === 'D') {
        if (si >= 79) dive.pgAfterSi = 'A'
        if (si <= 78 && si >= 31) dive.pgAfterSi = 'B'
        if (si <= 30 && si >= 9) dive.pgAfterSi = 'C'
        if (si <= 8 && si >= 0) dive.pgAfterSi = 'D'
    } else if (pg === 'E') {
        if (si >= 88) dive.pgAfterSi = 'A'
        if (si <= 87 && si >= 39) dive.pgAfterSi = 'B'
        if (si <= 38 && si >= 17) dive.pgAfterSi = 'C'
        if (si <= 16 && si >= 8) dive.pgAfterSi = 'D'
        if (si <= 7 && si >= 0) dive.pgAfterSi = 'E'
    } else if (pg === 'F') {
        if (si >= 95) dive.pgAfterSi = 'A'
        if (si <= 94 && si >= 47) dive.pgAfterSi = 'B'
        if (si <= 46 && si >= 23) dive.pgAfterSi = 'C'
        if (si <= 24 && si >= 16) dive.pgAfterSi = 'D'
        if (si <= 15 && si >= 8) dive.pgAfterSi = 'E'
        if (si <= 8 && si >= 0) dive.pgAfterSi = 'F'
    } else if (pg === 'G') {
        if (si >= 102) dive.pgAfterSi = 'A'
        if (si <= 101 && si >= 54) dive.pgAfterSi = 'B'
        if (si <= 53 && si >= 32) dive.pgAfterSi = 'C'
        if (si <= 31 && si >= 23) dive.pgAfterSi = 'D'
        if (si <= 22 && si >= 14) dive.pgAfterSi = 'E'
        if (si <= 13 && si >= 7) dive.pgAfterSi = 'F'
        if (si <= 6 && si >= 0) dive.pgAfterSi = 'G'
    } else if (pg === 'H') {
        if (si >= 108) dive.pgAfterSi = 'A'
        if (si <= 107 && si >= 60) dive.pgAfterSi = 'B'
        if (si <= 59 && si >= 38) dive.pgAfterSi = 'C'
        if (si <= 37 && si >= 29) dive.pgAfterSi = 'D'
        if (si <= 28 && si >= 21) dive.pgAfterSi = 'E'
        if (si <= 20 && si >= 13) dive.pgAfterSi = 'F'
        if (si <= 12 && si >= 6) dive.pgAfterSi = 'G'
        if (si <= 5 && si >= 0) dive.pgAfterSi = 'H'
    } else if (pg === 'I') {
        if (si >= 114) dive.pgAfterSi = 'A'
        if (si <= 113 && si >= 66) dive.pgAfterSi = 'B'
        if (si <= 65 && si >= 44) dive.pgAfterSi = 'C'
        if (si <= 43 && si >= 35) dive.pgAfterSi = 'D'
        if (si <= 34 && si >= 27) dive.pgAfterSi = 'E'
        if (si <= 26 && si >= 19) dive.pgAfterSi = 'F'
        if (si <= 18 && si >= 12) dive.pgAfterSi = 'G'
        if (si <= 11 && si >= 6) dive.pgAfterSi = 'H'
        if (si <= 5 && si >= 0) dive.pgAfterSi = 'I'
    } else if (pg === 'J') {
        if (si >= 120) dive.pgAfterSi = 'A'
        if (si <= 119 && si >= 72) dive.pgAfterSi = 'B'
        if (si <= 71 && si >= 50) dive.pgAfterSi = 'C'
        if (si <= 49 && si >= 41) dive.pgAfterSi = 'D'
        if (si <= 40 && si >= 32) dive.pgAfterSi = 'E'
        if (si <= 31 && si >= 25) dive.pgAfterSi = 'F'
        if (si <= 24 && si >= 18) dive.pgAfterSi = 'G'
        if (si <= 17 && si >= 12) dive.pgAfterSi = 'H'
        if (si <= 11 && si >= 6) dive.pgAfterSi = 'I'
        if (si <= 5 && si >= 0) dive.pgAfterSi = 'J'
    } else if (pg === 'K') {
        if (si >= 125) dive.pgAfterSi = 'A'
        if (si <= 124 && si >= 77) dive.pgAfterSi = 'B'
        if (si <= 76 && si >= 55) dive.pgAfterSi = 'C'
        if (si <= 54 && si >= 46) dive.pgAfterSi = 'D'
        if (si <= 45 && si >= 38) dive.pgAfterSi = 'E'
        if (si <= 37 && si >= 30) dive.pgAfterSi = 'F'
        if (si <= 29 && si >= 23) dive.pgAfterSi = 'G'
        if (si <= 22 && si >= 17) dive.pgAfterSi = 'H'
        if (si <= 16 && si >= 11) dive.pgAfterSi = 'I'
        if (si <= 10 && si >= 5) dive.pgAfterSi = 'J'
        if (si <= 4 && si >= 0) dive.pgAfterSi = 'K'
    } else if (pg === 'L') {
        if (si >= 130) dive.pgAfterSi = 'A'
        if (si <= 129 && si >= 82) dive.pgAfterSi = 'B'
        if (si <= 81 && si >= 60) dive.pgAfterSi = 'C'
        if (si <= 59 && si >= 51) dive.pgAfterSi = 'D'
        if (si <= 50 && si >= 43) dive.pgAfterSi = 'E'
        if (si <= 42 && si >= 35) dive.pgAfterSi = 'F'
        if (si <= 34 && si >= 28) dive.pgAfterSi = 'G'
        if (si <= 27 && si >= 22) dive.pgAfterSi = 'H'
        if (si <= 21 && si >= 16) dive.pgAfterSi = 'I'
        if (si <= 15 && si >= 10) dive.pgAfterSi = 'J'
        if (si <= 9 && si >= 5) dive.pgAfterSi = 'K'
        if (si <= 4 && si >= 0) dive.pgAfterSi = 'L'
    } else if (pg === 'M') {
        if (si >= 135) dive.pgAfterSi = 'A'
        if (si <= 134 && si >= 86) dive.pgAfterSi = 'B'
        if (si <= 85 && si >= 65) dive.pgAfterSi = 'C'
        if (si <= 64 && si >= 56) dive.pgAfterSi = 'D'
        if (si <= 55 && si >= 47) dive.pgAfterSi = 'E'
        if (si <= 46 && si >= 40) dive.pgAfterSi = 'F'
        if (si <= 39 && si >= 33) dive.pgAfterSi = 'G'
        if (si <= 32 && si >= 26) dive.pgAfterSi = 'H'
        if (si <= 25 && si >= 20) dive.pgAfterSi = 'I'
        if (si <= 19 && si >= 15) dive.pgAfterSi = 'J'
        if (si <= 14 && si >= 10) dive.pgAfterSi = 'K'
        if (si <= 9 && si >= 5) dive.pgAfterSi = 'L'
        if (si <= 4 && si >= 0) dive.pgAfterSi = 'M'
    } else if (pg === 'N') {
        if (si >= 139) dive.pgAfterSi = 'A'
        if (si <= 138 && si >= 91) dive.pgAfterSi = 'B'
        if (si <= 90 && si >= 69) dive.pgAfterSi = 'C'
        if (si <= 68 && si >= 60) dive.pgAfterSi = 'D'
        if (si <= 59 && si >= 52) dive.pgAfterSi = 'E'
        if (si <= 51 && si >= 44) dive.pgAfterSi = 'F'
        if (si <= 43 && si >= 37) dive.pgAfterSi = 'G'
        if (si <= 36 && si >= 31) dive.pgAfterSi = 'H'
        if (si <= 30 && si >= 25) dive.pgAfterSi = 'I'
        if (si <= 24 && si >= 19) dive.pgAfterSi = 'J'
        if (si <= 18 && si >= 14) dive.pgAfterSi = 'K'
        if (si <= 13 && si >= 9) dive.pgAfterSi = 'L'
        if (si <= 8 && si >= 4) dive.pgAfterSi = 'M'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'N'
    } else if (pg === 'O') {
        if (si >= 144) dive.pgAfterSi = 'A'
        if (si <= 143 && si >= 95) dive.pgAfterSi = 'B'
        if (si <= 94 && si >= 73) dive.pgAfterSi = 'C'
        if (si <= 72 && si >= 64) dive.pgAfterSi = 'D'
        if (si <= 63 && si >= 56) dive.pgAfterSi = 'E'
        if (si <= 55 && si >= 48) dive.pgAfterSi = 'F'
        if (si <= 47 && si >= 42) dive.pgAfterSi = 'G'
        if (si <= 41 && si >= 35) dive.pgAfterSi = 'H'
        if (si <= 34 && si >= 29) dive.pgAfterSi = 'I'
        if (si <= 28 && si >= 24) dive.pgAfterSi = 'J'
        if (si <= 23 && si >= 18) dive.pgAfterSi = 'K'
        if (si <= 17 && si >= 13) dive.pgAfterSi = 'L'
        if (si <= 12 && si >= 9) dive.pgAfterSi = 'M'
        if (si <= 8 && si >= 4) dive.pgAfterSi = 'N'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'O'
    } else if (pg === 'P') {
        if (si >= 148) dive.pgAfterSi = 'A'
        if (si <= 147 && si >= 99) dive.pgAfterSi = 'B'
        if (si <= 98 && si >= 77) dive.pgAfterSi = 'C'
        if (si <= 76 && si >= 68) dive.pgAfterSi = 'D'
        if (si <= 67 && si >= 60) dive.pgAfterSi = 'E'
        if (si <= 59 && si >= 52) dive.pgAfterSi = 'F'
        if (si <= 51 && si >= 46) dive.pgAfterSi = 'G'
        if (si <= 45 && si >= 39) dive.pgAfterSi = 'H'
        if (si <= 38 && si >= 33) dive.pgAfterSi = 'I'
        if (si <= 32 && si >= 28) dive.pgAfterSi = 'J'
        if (si <= 27 && si >= 22) dive.pgAfterSi = 'K'
        if (si <= 21 && si >= 17) dive.pgAfterSi = 'L'
        if (si <= 16 && si >= 13) dive.pgAfterSi = 'M'
        if (si <= 12 && si >= 8) dive.pgAfterSi = 'N'
        if (si <= 7 && si >= 4) dive.pgAfterSi = 'O'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'P'
    } else if (pg === 'Q') {
        if (si >= 151) dive.pgAfterSi = 'A'
        if (si <= 150 && si >= 103) dive.pgAfterSi = 'B'
        if (si <= 102 && si >= 81) dive.pgAfterSi = 'C'
        if (si <= 80 && si >= 72) dive.pgAfterSi = 'D'
        if (si <= 71 && si >= 64) dive.pgAfterSi = 'E'
        if (si <= 63 && si >= 56) dive.pgAfterSi = 'F'
        if (si <= 55 && si >= 49) dive.pgAfterSi = 'G'
        if (si <= 48 && si >= 43) dive.pgAfterSi = 'H'
        if (si <= 42 && si >= 37) dive.pgAfterSi = 'I'
        if (si <= 36 && si >= 31) dive.pgAfterSi = 'J'
        if (si <= 30 && si >= 26) dive.pgAfterSi = 'K'
        if (si <= 25 && si >= 21) dive.pgAfterSi = 'L'
        if (si <= 20 && si >= 17) dive.pgAfterSi = 'M'
        if (si <= 16 && si >= 12) dive.pgAfterSi = 'N'
        if (si <= 11 && si >= 8) dive.pgAfterSi = 'O'
        if (si <= 7 && si >= 4) dive.pgAfterSi = 'P'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'Q'
    } else if (pg === 'R') {
        if (si >= 155) dive.pgAfterSi = 'A'
        if (si <= 154 && si >= 107) dive.pgAfterSi = 'B'
        if (si <= 106 && si >= 85) dive.pgAfterSi = 'C'
        if (si <= 84 && si >= 76) dive.pgAfterSi = 'D'
        if (si <= 75 && si >= 68) dive.pgAfterSi = 'E'
        if (si <= 67 && si >= 60) dive.pgAfterSi = 'F'
        if (si <= 59 && si >= 53) dive.pgAfterSi = 'G'
        if (si <= 52 && si >= 47) dive.pgAfterSi = 'H'
        if (si <= 46 && si >= 41) dive.pgAfterSi = 'I'
        if (si <= 40 && si >= 35) dive.pgAfterSi = 'J'
        if (si <= 34 && si >= 30) dive.pgAfterSi = 'K'
        if (si <= 29 && si >= 25) dive.pgAfterSi = 'L'
        if (si <= 24 && si >= 20) dive.pgAfterSi = 'M'
        if (si <= 19 && si >= 16) dive.pgAfterSi = 'N'
        if (si <= 15 && si >= 12) dive.pgAfterSi = 'O'
        if (si <= 11 && si >= 8) dive.pgAfterSi = 'P'
        if (si <= 7 && si >= 4) dive.pgAfterSi = 'Q'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'R'
    } else if (pg === 'S') {
        if (si >= 159) dive.pgAfterSi = 'A'
        if (si <= 158 && si >= 110) dive.pgAfterSi = 'B'
        if (si <= 109 && si >= 88) dive.pgAfterSi = 'C'
        if (si <= 87 && si >= 79) dive.pgAfterSi = 'D'
        if (si <= 78 && si >= 71) dive.pgAfterSi = 'E'
        if (si <= 70 && si >= 64) dive.pgAfterSi = 'F'
        if (si <= 63 && si >= 57) dive.pgAfterSi = 'G'
        if (si <= 56 && si >= 50) dive.pgAfterSi = 'H'
        if (si <= 49 && si >= 44) dive.pgAfterSi = 'I'
        if (si <= 43 && si >= 39) dive.pgAfterSi = 'J'
        if (si <= 38 && si >= 33) dive.pgAfterSi = 'K'
        if (si <= 32 && si >= 28) dive.pgAfterSi = 'L'
        if (si <= 27 && si >= 24) dive.pgAfterSi = 'M'
        if (si <= 23 && si >= 19) dive.pgAfterSi = 'N'
        if (si <= 18 && si >= 15) dive.pgAfterSi = 'O'
        if (si <= 14 && si >= 11) dive.pgAfterSi = 'P'
        if (si <= 10 && si >= 7) dive.pgAfterSi = 'Q'
        if (si <= 6 && si >= 4) dive.pgAfterSi = 'R'
        if (si <= 3 && si >= 0) dive.pgAfterSi = 'S'
    } else if (pg === 'T') {
        if (si >= 162) dive.pgAfterSi = 'A'
        if (si <= 161 && si >= 114) dive.pgAfterSi = 'B'
        if (si <= 113 && si >= 92) dive.pgAfterSi = 'C'
        if (si <= 91 && si >= 83) dive.pgAfterSi = 'D'
        if (si <= 82 && si >= 74) dive.pgAfterSi = 'E'
        if (si <= 73 && si >= 67) dive.pgAfterSi = 'F'
        if (si <= 66 && si >= 60) dive.pgAfterSi = 'G'
        if (si <= 59 && si >= 54) dive.pgAfterSi = 'H'
        if (si <= 53 && si >= 48) dive.pgAfterSi = 'I'
        if (si <= 47 && si >= 42) dive.pgAfterSi = 'J'
        if (si <= 41 && si >= 37) dive.pgAfterSi = 'K'
        if (si <= 36 && si >= 32) dive.pgAfterSi = 'L'
        if (si <= 31 && si >= 27) dive.pgAfterSi = 'M'
        if (si <= 26 && si >= 23) dive.pgAfterSi = 'N'
        if (si <= 22 && si >= 18) dive.pgAfterSi = 'O'
        if (si <= 17 && si >= 14) dive.pgAfterSi = 'P'
        if (si <= 13 && si >= 11) dive.pgAfterSi = 'Q'
        if (si <= 10 && si >= 7) dive.pgAfterSi = 'R'
        if (si <= 6 && si >= 3) dive.pgAfterSi = 'S'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'T'
    } else if (pg === 'U') {
        if (si >= 165) dive.pgAfterSi = 'A'
        if (si <= 164 && si >= 117) dive.pgAfterSi = 'B'
        if (si <= 116 && si >= 95) dive.pgAfterSi = 'C'
        if (si <= 94 && si >= 86) dive.pgAfterSi = 'D'
        if (si <= 85 && si >= 78) dive.pgAfterSi = 'E'
        if (si <= 77 && si >= 70) dive.pgAfterSi = 'F'
        if (si <= 69 && si >= 63) dive.pgAfterSi = 'G'
        if (si <= 62 && si >= 57) dive.pgAfterSi = 'H'
        if (si <= 56 && si >= 51) dive.pgAfterSi = 'I'
        if (si <= 50 && si >= 45) dive.pgAfterSi = 'J'
        if (si <= 44 && si >= 40) dive.pgAfterSi = 'K'
        if (si <= 39 && si >= 35) dive.pgAfterSi = 'L'
        if (si <= 34 && si >= 30) dive.pgAfterSi = 'M'
        if (si <= 29 && si >= 26) dive.pgAfterSi = 'N'
        if (si <= 25 && si >= 22) dive.pgAfterSi = 'O'
        if (si <= 21 && si >= 18) dive.pgAfterSi = 'P'
        if (si <= 17 && si >= 14) dive.pgAfterSi = 'Q'
        if (si <= 13 && si >= 10) dive.pgAfterSi = 'R'
        if (si <= 9 && si >= 7) dive.pgAfterSi = 'S'
        if (si <= 6 && si >= 3) dive.pgAfterSi = 'T'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'U'
    } else if (pg === 'V') {
        if (si >= 168) dive.pgAfterSi = 'A'
        if (si <= 167 && si >= 120) dive.pgAfterSi = 'B'
        if (si <= 119 && si >= 98) dive.pgAfterSi = 'C'
        if (si <= 97 && si >= 89) dive.pgAfterSi = 'D'
        if (si <= 88 && si >= 81) dive.pgAfterSi = 'E'
        if (si <= 80 && si >= 73) dive.pgAfterSi = 'F'
        if (si <= 72 && si >= 66) dive.pgAfterSi = 'G'
        if (si <= 65 && si >= 60) dive.pgAfterSi = 'H'
        if (si <= 59 && si >= 54) dive.pgAfterSi = 'I'
        if (si <= 53 && si >= 48) dive.pgAfterSi = 'J'
        if (si <= 47 && si >= 43) dive.pgAfterSi = 'K'
        if (si <= 42 && si >= 38) dive.pgAfterSi = 'L'
        if (si <= 37 && si >= 34) dive.pgAfterSi = 'M'
        if (si <= 33 && si >= 29) dive.pgAfterSi = 'N'
        if (si <= 28 && si >= 25) dive.pgAfterSi = 'O'
        if (si <= 24 && si >= 21) dive.pgAfterSi = 'P'
        if (si <= 20 && si >= 17) dive.pgAfterSi = 'Q'
        if (si <= 16 && si >= 13) dive.pgAfterSi = 'R'
        if (si <= 12 && si >= 10) dive.pgAfterSi = 'S'
        if (si <= 9 && si >= 6) dive.pgAfterSi = 'T'
        if (si <= 5 && si >= 3) dive.pgAfterSi = 'U'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'V'
    } else if (pg === 'W') {
        if (si >= 171) dive.pgAfterSi = 'A'
        if (si <= 170 && si >= 123) dive.pgAfterSi = 'B'
        if (si <= 122 && si >= 101) dive.pgAfterSi = 'C'
        if (si <= 100 && si >= 92) dive.pgAfterSi = 'D'
        if (si <= 91 && si >= 84) dive.pgAfterSi = 'E'
        if (si <= 83 && si >= 76) dive.pgAfterSi = 'F'
        if (si <= 75 && si >= 69) dive.pgAfterSi = 'G'
        if (si <= 68 && si >= 63) dive.pgAfterSi = 'H'
        if (si <= 62 && si >= 57) dive.pgAfterSi = 'I'
        if (si <= 56 && si >= 51) dive.pgAfterSi = 'J'
        if (si <= 50 && si >= 46) dive.pgAfterSi = 'K'
        if (si <= 45 && si >= 41) dive.pgAfterSi = 'L'
        if (si <= 40 && si >= 37) dive.pgAfterSi = 'M'
        if (si <= 36 && si >= 32) dive.pgAfterSi = 'N'
        if (si <= 31 && si >= 28) dive.pgAfterSi = 'O'
        if (si <= 27 && si >= 24) dive.pgAfterSi = 'P'
        if (si <= 23 && si >= 20) dive.pgAfterSi = 'Q'
        if (si <= 19 && si >= 16) dive.pgAfterSi = 'R'
        if (si <= 15 && si >= 13) dive.pgAfterSi = 'S'
        if (si <= 12 && si >= 9) dive.pgAfterSi = 'T'
        if (si <= 8 && si >= 5) dive.pgAfterSi = 'U'
        if (si <= 5 && si >= 3) dive.pgAfterSi = 'V'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'W'
    } else if (pg === 'X') {
        if (si >= 174) dive.pgAfterSi = 'A'
        if (si <= 173 && si >= 126) dive.pgAfterSi = 'B'
        if (si <= 125 && si >= 104) dive.pgAfterSi = 'C'
        if (si <= 103 && si >= 95) dive.pgAfterSi = 'D'
        if (si <= 94 && si >= 87) dive.pgAfterSi = 'E'
        if (si <= 86 && si >= 79) dive.pgAfterSi = 'F'
        if (si <= 78 && si >= 72) dive.pgAfterSi = 'G'
        if (si <= 71 && si >= 66) dive.pgAfterSi = 'H'
        if (si <= 65 && si >= 60) dive.pgAfterSi = 'I'
        if (si <= 59 && si >= 54) dive.pgAfterSi = 'J'
        if (si <= 53 && si >= 49) dive.pgAfterSi = 'K'
        if (si <= 48 && si >= 44) dive.pgAfterSi = 'L'
        if (si <= 43 && si >= 40) dive.pgAfterSi = 'M'
        if (si <= 39 && si >= 35) dive.pgAfterSi = 'N'
        if (si <= 34 && si >= 31) dive.pgAfterSi = 'O'
        if (si <= 30 && si >= 27) dive.pgAfterSi = 'P'
        if (si <= 26 && si >= 23) dive.pgAfterSi = 'Q'
        if (si <= 22 && si >= 19) dive.pgAfterSi = 'R'
        if (si <= 18 && si >= 16) dive.pgAfterSi = 'S'
        if (si <= 15 && si >= 12) dive.pgAfterSi = 'T'
        if (si <= 11 && si >= 9) dive.pgAfterSi = 'U'
        if (si <= 8 && si >= 6) dive.pgAfterSi = 'V'
        if (si <= 5 && si >= 3) dive.pgAfterSi = 'W'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'X'
    } else if (pg === 'Y') {
        if (si >= 177) dive.pgAfterSi = 'A'
        if (si <= 176 && si >= 129) dive.pgAfterSi = 'B'
        if (si <= 128 && si >= 107) dive.pgAfterSi = 'C'
        if (si <= 106 && si >= 98) dive.pgAfterSi = 'D'
        if (si <= 97 && si >= 90) dive.pgAfterSi = 'E'
        if (si <= 89 && si >= 82) dive.pgAfterSi = 'F'
        if (si <= 81 && si >= 75) dive.pgAfterSi = 'G'
        if (si <= 74 && si >= 69) dive.pgAfterSi = 'H'
        if (si <= 68 && si >= 63) dive.pgAfterSi = 'I'
        if (si <= 62 && si >= 57) dive.pgAfterSi = 'J'
        if (si <= 56 && si >= 52) dive.pgAfterSi = 'K'
        if (si <= 51 && si >= 47) dive.pgAfterSi = 'L'
        if (si <= 46 && si >= 42) dive.pgAfterSi = 'M'
        if (si <= 41 && si >= 38) dive.pgAfterSi = 'N'
        if (si <= 37 && si >= 34) dive.pgAfterSi = 'O'
        if (si <= 33 && si >= 30) dive.pgAfterSi = 'P'
        if (si <= 29 && si >= 26) dive.pgAfterSi = 'Q'
        if (si <= 25 && si >= 22) dive.pgAfterSi = 'R'
        if (si <= 21 && si >= 19) dive.pgAfterSi = 'S'
        if (si <= 18 && si >= 15) dive.pgAfterSi = 'T'
        if (si <= 14 && si >= 12) dive.pgAfterSi = 'U'
        if (si <= 11 && si >= 9) dive.pgAfterSi = 'V'
        if (si <= 8 && si >= 6) dive.pgAfterSi = 'W'
        if (si <= 5 && si >= 3) dive.pgAfterSi = 'X'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'Y'
    } else if (pg === 'Z') {
        if (si >= 180) dive.pgAfterSi = 'A'
        if (si <= 179 && si >= 132) dive.pgAfterSi = 'B'
        if (si <= 131 && si >= 110) dive.pgAfterSi = 'C'
        if (si <= 109 && si >= 101) dive.pgAfterSi = 'D'
        if (si <= 100 && si >= 92) dive.pgAfterSi = 'E'
        if (si <= 91 && si >= 85) dive.pgAfterSi = 'F'
        if (si <= 84 && si >= 78) dive.pgAfterSi = 'G'
        if (si <= 77 && si >= 72) dive.pgAfterSi = 'H'
        if (si <= 71 && si >= 66) dive.pgAfterSi = 'I'
        if (si <= 65 && si >= 60) dive.pgAfterSi = 'J'
        if (si <= 59 && si >= 55) dive.pgAfterSi = 'K'
        if (si <= 54 && si >= 50) dive.pgAfterSi = 'L'
        if (si <= 49 && si >= 45) dive.pgAfterSi = 'M'
        if (si <= 44 && si >= 41) dive.pgAfterSi = 'N'
        if (si <= 40 && si >= 36) dive.pgAfterSi = 'O'
        if (si <= 35 && si >= 32) dive.pgAfterSi = 'P'
        if (si <= 31 && si >= 29) dive.pgAfterSi = 'Q'
        if (si <= 28 && si >= 25) dive.pgAfterSi = 'R'
        if (si <= 24 && si >= 21) dive.pgAfterSi = 'S'
        if (si <= 20 && si >= 18) dive.pgAfterSi = 'T'
        if (si <= 17 && si >= 15) dive.pgAfterSi = 'U'
        if (si <= 14 && si >= 12) dive.pgAfterSi = 'V'
        if (si <= 11 && si >= 9) dive.pgAfterSi = 'W'
        if (si <= 8 && si >= 6) dive.pgAfterSi = 'X'
        if (si <= 5 && si >= 3) dive.pgAfterSi = 'Y'
        if (si <= 2 && si >= 0) dive.pgAfterSi = 'Z'
    }

    if (step === 2) updateDive2(dive)
    else if (step === 3) updateDive3(dive)
}