// Sets residual nitrogen time, given starting pressure group and depth of next dive.

export const GetRNTN36 = (step, inputDepth, newPg) => {
    const depth = inputDepth
    const startPg = newPg
    if (step === 1) { return 0 }
    else if (depth <= 50) {
        if (startPg === 'A') return 10
        if (startPg === 'B') return 20
        if (startPg === 'C') return 26
        if (startPg === 'D') return 30
        if (startPg === 'E') return 33
        if (startPg === 'F') return 37
        if (startPg === 'G') return 41
        if (startPg === 'H') return 46
        if (startPg === 'I') return 50
        if (startPg === 'J') return 55
        if (startPg === 'K') return 60
        if (startPg === 'L') return 65
        if (startPg === 'M') return 71
        if (startPg === 'N') return 77
        if (startPg === 'O') return 83
        if (startPg === 'P') return 90
        if (startPg === 'Q') return 97
        if (startPg === 'R') return 106
        if (startPg === 'S') return 115
        if (startPg === 'T') return 125
        if (startPg === 'U') return 137
        if (startPg === 'V') return 150
        if (startPg === 'W') return 166
        if (startPg === 'X') return 186
        if (startPg === 'Y') return 211
        if (startPg === 'Z') return 220
    } else if (depth <= 55) {
        if (startPg === 'A') return 9
        if (startPg === 'B') return 17
        if (startPg === 'C') return 23
        if (startPg === 'D') return 26
        if (startPg === 'E') return 29
        if (startPg === 'F') return 32
        if (startPg === 'G') return 36
        if (startPg === 'H') return 39
        if (startPg === 'I') return 43
        if (startPg === 'J') return 47
        if (startPg === 'K') return 51
        if (startPg === 'L') return 55
        if (startPg === 'M') return 60
        if (startPg === 'N') return 64
        if (startPg === 'O') return 69
        if (startPg === 'P') return 75
        if (startPg === 'Q') return 80
        if (startPg === 'R') return 86
        if (startPg === 'S') return 93
        if (startPg === 'T') return 100
        if (startPg === 'U') return 107
        if (startPg === 'V') return 115
        if (startPg === 'W') return 125
        if (startPg === 'X') return 135
        if (startPg === 'Y') return 146
        if (startPg === 'Z') return 155
    } else if (depth <= 60) {
        if (startPg === 'A') return 8
        if (startPg === 'B') return 15
        if (startPg === 'C') return 20
        if (startPg === 'D') return 23
        if (startPg === 'E') return 26
        if (startPg === 'F') return 29
        if (startPg === 'G') return 32
        if (startPg === 'H') return 35
        if (startPg === 'I') return 38
        if (startPg === 'J') return 41
        if (startPg === 'K') return 45
        if (startPg === 'L') return 48
        if (startPg === 'M') return 52
        if (startPg === 'N') return 56
        if (startPg === 'O') return 60
        if (startPg === 'P') return 64
        if (startPg === 'Q') return 68
        if (startPg === 'R') return 73
        if (startPg === 'S') return 78
        if (startPg === 'T') return 83
        if (startPg === 'U') return 89
        if (startPg === 'V') return 95
        if (startPg === 'W') return 101
        if (startPg === 'X') return 108
        if (startPg === 'Y') return 115
    } else if (depth <= 65) {
        if (startPg === 'A') return 7
        if (startPg === 'B') return 14
        if (startPg === 'C') return 18
        if (startPg === 'D') return 21
        if (startPg === 'E') return 23
        if (startPg === 'F') return 26
        if (startPg === 'G') return 28
        if (startPg === 'H') return 31
        if (startPg === 'I') return 34
        if (startPg === 'J') return 37
        if (startPg === 'K') return 40
        if (startPg === 'L') return 43
        if (startPg === 'M') return 46
        if (startPg === 'N') return 49
        if (startPg === 'O') return 52
        if (startPg === 'P') return 56
        if (startPg === 'Q') return 60
        if (startPg === 'R') return 64
        if (startPg === 'S') return 68
        if (startPg === 'T') return 72
        if (startPg === 'U') return 76
        if (startPg === 'V') return 81
        if (startPg === 'W') return 86
        if (startPg === 'X') return 90
    } else if (depth <= 70) {
        if (startPg === 'A') return 7
        if (startPg === 'B') return 13
        if (startPg === 'C') return 17
        if (startPg === 'D') return 19
        if (startPg === 'E') return 21
        if (startPg === 'F') return 23
        if (startPg === 'G') return 26
        if (startPg === 'H') return 28
        if (startPg === 'I') return 31
        if (startPg === 'J') return 33
        if (startPg === 'K') return 36
        if (startPg === 'L') return 38
        if (startPg === 'M') return 41
        if (startPg === 'N') return 44
        if (startPg === 'O') return 47
        if (startPg === 'P') return 50
        if (startPg === 'Q') return 53
        if (startPg === 'R') return 56
        if (startPg === 'S') return 60
        if (startPg === 'T') return 63
        if (startPg === 'U') return 67
        if (startPg === 'V') return 71
        if (startPg === 'W') return 75
    } else if (depth <= 80) {
        if (startPg === 'A') return 6
        if (startPg === 'B') return 11
        if (startPg === 'C') return 14
        if (startPg === 'D') return 16
        if (startPg === 'E') return 18
        if (startPg === 'F') return 20
        if (startPg === 'G') return 22
        if (startPg === 'H') return 24
        if (startPg === 'I') return 26
        if (startPg === 'J') return 28
        if (startPg === 'K') return 30
        if (startPg === 'L') return 32
        if (startPg === 'M') return 34
        if (startPg === 'N') return 36
        if (startPg === 'O') return 39
        if (startPg === 'P') return 41
        if (startPg === 'Q') return 43
        if (startPg === 'R') return 46
        if (startPg === 'S') return 48
        if (startPg === 'T') return 51
        if (startPg === 'U') return 53
        if (startPg === 'V') return 55
    } else if (depth <= 90) {
        if (startPg === 'A') return 5
        if (startPg === 'B') return 9
        if (startPg === 'C') return 12
        if (startPg === 'D') return 14
        if (startPg === 'E') return 15
        if (startPg === 'F') return 17
        if (startPg === 'G') return 19
        if (startPg === 'H') return 20
        if (startPg === 'I') return 22
        if (startPg === 'J') return 24
        if (startPg === 'K') return 25
        if (startPg === 'L') return 27
        if (startPg === 'M') return 29
        if (startPg === 'N') return 31
        if (startPg === 'O') return 33
        if (startPg === 'P') return 35
        if (startPg === 'Q') return 37
        if (startPg === 'R') return 38
        if (startPg === 'S') return 39
        if (startPg === 'T') return 40
    } else if (depth <= 100) {
        if (startPg === 'A') return 4
        if (startPg === 'B') return 8
        if (startPg === 'C') return 11
        if (startPg === 'D') return 12
        if (startPg === 'E') return 14
        if (startPg === 'F') return 15
        if (startPg === 'G') return 16
        if (startPg === 'H') return 18
        if (startPg === 'I') return 19
        if (startPg === 'J') return 21
        if (startPg === 'K') return 22
        if (startPg === 'L') return 24
        if (startPg === 'M') return 25
        if (startPg === 'N') return 27
        if (startPg === 'O') return 29
        if (startPg === 'P') return 30
        if (startPg === 'Q') return 32
        if (startPg === 'R') return 34
        if (startPg === 'S') return 35
    } else if (depth <= 110) {
        if (startPg === 'A') return 4
        if (startPg === 'B') return 7
        if (startPg === 'C') return 10
        if (startPg === 'D') return 11
        if (startPg === 'E') return 12
        if (startPg === 'F') return 13
        if (startPg === 'G') return 15
        if (startPg === 'H') return 16
        if (startPg === 'I') return 17
        if (startPg === 'J') return 18
        if (startPg === 'K') return 20
        if (startPg === 'L') return 21
        if (startPg === 'M') return 22
        if (startPg === 'N') return 24
        if (startPg === 'O') return 25
        if (startPg === 'P') return 27
        if (startPg === 'Q') return 28
        if (startPg === 'R') return 29
    }
}