import { GetRNTN32 } from "./GetRNTN32"

// Sets Pressure Group, safety stop boolean, no deco limit boolean, minutes to no deco time, and specifies which dive to update.

export const GetPGN32 = (input, step, currentDive, setAndUpdate) => {
    let rnt = input.rnt
    if (step === 2 || step === 3) rnt = GetRNTN32(step, input.depth, currentDive.pgAfterSi)
    let tbt = (input.abt + rnt)
    const depth = input.depth
    if (depth <= 45) {
        if (tbt <= 10) setAndUpdate('A', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('B', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 26) setAndUpdate('C', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 30) setAndUpdate('D', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 34) setAndUpdate('E', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 37) setAndUpdate('F', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 41) setAndUpdate('G', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 46) setAndUpdate('H', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 50) setAndUpdate('I', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 55) setAndUpdate('J', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 60) setAndUpdate('K', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 65) setAndUpdate('L', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 71) setAndUpdate('M', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 77) setAndUpdate('N', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 83) setAndUpdate('O', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 90) setAndUpdate('P', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 98) setAndUpdate('Q', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 106) setAndUpdate('R', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 115) setAndUpdate('S', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 126) setAndUpdate('T', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 138) setAndUpdate('U', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 151) setAndUpdate('V', false, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 167) setAndUpdate('W', true, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 187) setAndUpdate('X', true, false, (tbt - 220), input, step, rnt)
        else if (tbt <= 213) setAndUpdate('Y', true, false, (tbt - 220), input, step, rnt)
        else if (tbt > 213) setAndUpdate('Z', true, true, (tbt - 220), input, step, rnt)
    }
    else if (depth <= 50) {
        if (tbt <= 9) setAndUpdate('A', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('B', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('C', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 26) setAndUpdate('D', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 29) setAndUpdate('E', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 32) setAndUpdate('F', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 36) setAndUpdate('G', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 39) setAndUpdate('H', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 43) setAndUpdate('I', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 47) setAndUpdate('J', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 51) setAndUpdate('K', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 55) setAndUpdate('L', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 59) setAndUpdate('M', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 64) setAndUpdate('N', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 69) setAndUpdate('O', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 74) setAndUpdate('P', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 80) setAndUpdate('Q', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 85) setAndUpdate('R', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 92) setAndUpdate('S', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 99) setAndUpdate('T', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 106) setAndUpdate('U', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 114) setAndUpdate('V', false, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 123) setAndUpdate('W', true, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 133) setAndUpdate('X', true, false, (tbt - 155), input, step, rnt)
        else if (tbt <= 145) setAndUpdate('Y', true, false, (tbt - 155), input, step, rnt)
        else if (tbt > 145) setAndUpdate('Z', true, true, (tbt - 155), input, step, rnt)
    }
    else if (depth <= 55) {
        if (tbt <= 8) setAndUpdate('A', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('B', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('C', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('D', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 26) setAndUpdate('E', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 28) setAndUpdate('F', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 31) setAndUpdate('G', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 34) setAndUpdate('H', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 37) setAndUpdate('I', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 41) setAndUpdate('J', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 44) setAndUpdate('K', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 47) setAndUpdate('L', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 51) setAndUpdate('M', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 55) setAndUpdate('N', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 59) setAndUpdate('O', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 63) setAndUpdate('P', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 67) setAndUpdate('Q', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 72) setAndUpdate('R', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 77) setAndUpdate('S', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 82) setAndUpdate('T', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 87) setAndUpdate('U', false, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 93) setAndUpdate('V', true, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 99) setAndUpdate('W', true, false, (tbt - 110), input, step, rnt)
        else if (tbt <= 106) setAndUpdate('X', true, false, (tbt - 110), input, step, rnt)
        else if (tbt > 106) setAndUpdate('Y', true, true, (tbt - 110), input, step, rnt)
    }
    else if (depth <= 60) {
        if (tbt <= 7) setAndUpdate('A', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('B', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 18) setAndUpdate('C', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('D', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('E', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 25) setAndUpdate('F', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 28) setAndUpdate('G', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 30) setAndUpdate('H', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 33) setAndUpdate('I', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 36) setAndUpdate('J', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 39) setAndUpdate('K', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 42) setAndUpdate('L', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 45) setAndUpdate('M', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 48) setAndUpdate('N', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 51) setAndUpdate('O', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 55) setAndUpdate('P', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 58) setAndUpdate('Q', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 62) setAndUpdate('R', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 66) setAndUpdate('S', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 70) setAndUpdate('T', false, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 74) setAndUpdate('U', true, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 79) setAndUpdate('V', true, false, (tbt - 90), input, step, rnt)
        else if (tbt <= 84) setAndUpdate('W', true, false, (tbt - 90), input, step, rnt)
        else if (tbt > 84) setAndUpdate('X', true, true, (tbt - 90), input, step, rnt)
    }
    else if (depth <= 70) {
        if (tbt <= 6) setAndUpdate('A', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('B', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('C', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('D', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 19) setAndUpdate('E', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 21) setAndUpdate('F', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('G', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 25) setAndUpdate('H', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 27) setAndUpdate('I', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 29) setAndUpdate('J', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 32) setAndUpdate('K', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 34) setAndUpdate('L', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 36) setAndUpdate('M', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 39) setAndUpdate('N', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 41) setAndUpdate('O', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 44) setAndUpdate('P', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 46) setAndUpdate('Q', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 49) setAndUpdate('R', false, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 52) setAndUpdate('S', true, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 55) setAndUpdate('T', true, false, (tbt - 60), input, step, rnt)
        else if (tbt <= 58) setAndUpdate('U', true, false, (tbt - 60), input, step, rnt)
        else if (tbt > 58) setAndUpdate('V', true, true, (tbt - 60), input, step, rnt)
    }
    else if (depth <= 80) {
        if (tbt <= 5) setAndUpdate('A', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 10) setAndUpdate('B', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 13) setAndUpdate('C', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('D', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 16) setAndUpdate('E', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 18) setAndUpdate('F', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 19) setAndUpdate('G', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 21) setAndUpdate('H', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('I', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 25) setAndUpdate('J', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 27) setAndUpdate('K', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 28) setAndUpdate('L', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 30) setAndUpdate('M', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 32) setAndUpdate('N', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 34) setAndUpdate('O', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 36) setAndUpdate('P', false, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 38) setAndUpdate('Q', true, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 41) setAndUpdate('R', true, false, (tbt - 45), input, step, rnt)
        else if (tbt <= 43) setAndUpdate('S', true, false, (tbt - 45), input, step, rnt)
        else if (tbt > 43) setAndUpdate('T', true, true, (tbt - 45), input, step, rnt)
    }
    else if (depth <= 90) {
        if (tbt <= 5) setAndUpdate('A', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 8) setAndUpdate('B', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('C', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 13) setAndUpdate('D', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('E', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('F', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('G', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 18) setAndUpdate('H', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('I', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 21) setAndUpdate('J', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('K', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 24) setAndUpdate('L', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 26) setAndUpdate('M', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 28) setAndUpdate('N', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 29) setAndUpdate('O', false, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 31) setAndUpdate('P', true, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 33) setAndUpdate('Q', true, false, (tbt - 35), input, step, rnt)
        else if (tbt <= 34) setAndUpdate('R', true, false, (tbt - 35), input, step, rnt)
        else if (tbt > 34) setAndUpdate('S', true, true, (tbt - 35), input, step, rnt)
    }
    else if (depth <= 100) {
        if (tbt <= 4) setAndUpdate('A', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 7) setAndUpdate('B', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 10) setAndUpdate('C', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('D', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 12) setAndUpdate('E', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('F', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('G', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 16) setAndUpdate('H', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('I', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 19) setAndUpdate('J', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('K', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 22) setAndUpdate('L', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('M', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 24) setAndUpdate('N', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 26) setAndUpdate('O', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 27) setAndUpdate('P', true, false, (tbt - 30), input, step, rnt)
        else if (tbt <= 29) setAndUpdate('Q', true, false, (tbt - 30), input, step, rnt)
        else if (tbt > 29) setAndUpdate('R', true, true, (tbt - 30), input, step, rnt)
    }
    else if (depth <= 110) {
        if (tbt <= 4) setAndUpdate('A', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 7) setAndUpdate('B', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 9) setAndUpdate('C', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 10) setAndUpdate('D', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('E', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 12) setAndUpdate('F', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 13) setAndUpdate('G', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('H', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 16) setAndUpdate('I', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('J', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 18) setAndUpdate('K', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 19) setAndUpdate('L', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 20) setAndUpdate('M', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 22) setAndUpdate('N', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 23) setAndUpdate('O', true, false, (tbt - 25), input, step, rnt)
        else if (tbt <= 24) setAndUpdate('P', true, false, (tbt - 25), input, step, rnt)
        else if (tbt > 24) setAndUpdate('Q', true, true, (tbt - 25), input, step, rnt)
    }
    else if (depth <= 120) {
        if (tbt <= 3) setAndUpdate('A', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 6) setAndUpdate('B', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 8) setAndUpdate('C', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 9) setAndUpdate('D', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 10) setAndUpdate('E', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('F', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 12) setAndUpdate('G', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 13) setAndUpdate('H', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('I', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('J', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 16) setAndUpdate('K', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('L', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 18) setAndUpdate('M', true, false, (tbt - 20), input, step, rnt)
        else if (tbt <= 19) setAndUpdate('N', true, false, (tbt - 20), input, step, rnt)
        else if (tbt > 19) setAndUpdate('O', true, true, (tbt - 20), input, step, rnt)
    }
    else if (depth <= 130) {
        if (tbt <= 3) setAndUpdate('A', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 6) setAndUpdate('B', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 7) setAndUpdate('C', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 8) setAndUpdate('D', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 9) setAndUpdate('E', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 10) setAndUpdate('F', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 11) setAndUpdate('G', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 12) setAndUpdate('H', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 13) setAndUpdate('I', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 14) setAndUpdate('J', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 15) setAndUpdate('K', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 16) setAndUpdate('L', true, false, (tbt - 18), input, step, rnt)
        else if (tbt <= 17) setAndUpdate('M', true, false, (tbt - 18), input, step, rnt)
        else if (tbt > 17) setAndUpdate('N', true, true, (tbt - 18), input, step, rnt)
    }
}